{% set version = "4.14.1" %}

package:
  name: cgal-cpp
  version: {{ version }}

source:
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-{{ version }}/CGAL-{{ version }}.zip
  sha256: 0841eee63c1273f327ef1331facbafffa77b527d76e5933d07f6b315bc34e135

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - mpfr
    - eigen
  run:
    - boost-cpp
    - mpfr
    - eigen

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja
  files:
    - test
  commands:
    - echo on  # [win]
    - test -f ${PREFIX}/include/CGAL/AABB_tree.h  # [unix]
    - test -f ${PREFIX}/lib/libCGAL${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_INC%\CGAL\AABB_tree.h exit 1  # [win]

    # Builds a simple program
    - cd test

    - mkdir build_default
    - cd build_default
    - cmake .. -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [win]
    - cmake .. -G"$CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  # [unix]
    - cmake --build . --config Release
    - ./test_  # [unix]
    - test_.exe  # [win]
    - cd ..

    - mkdir build_ninja
    - cd build_ninja
    - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --config Release
    - ./test_  # [unix]
    - test_.exe  # [win]

about:
  home: http://www.cgal.org/
  license: GPL3/LGPL3
  summary: Computational Geometry Algorithms Library

extra:
  recipe-maintainers:
    - tadeu
