travis:
  secure:
    BINSTAR_TOKEN: qFL5CzYBqUi3sG/ICcFLROMpBl4pBOTjRf/oorJ+Cc2by8fRXk7mGHXc1JpqpvLV8uAVuHLqDqNJHOjmB41qBMmtxegURi7P9EpZb4jRTRn+7CuDvUrwZcuvHAQPj6aqczyKfqhRv2RF+6w5yNWKTFrk96FdtstH9r9btRPg1uyiM1Bn62x0VGFqAOU/2iIlGKsxd0T7TNGtZJCktylcC7xdEjs21MB8bEbahkrLogqgI5xC8kSCDPBvd2HiSQcLPkURwmJMEENgbKd2xKSF10WoB0Bt3skjnhsqbB7GHSrHStM/S7XrLim/OGMRPal7uO6CIeB73hF+4PXsG4OuposCVkh9YOkJqVy1ml0Q7EyyTNYk+6wqD+SQrVHpqnwJghd+fiLqdwwhSXvy9fxgx6fCsjQpzN7CjSscME36VrRaN36fu8TrReH/M1bL1jp60HVYponYjUxap0aNqBUf2Ag94/DvX+NMCU/MtO+Nj0+60LmLz7+4p3pdZ4wyrj52SoONhB4wnpwZGmyV/s/LpAshvYpOeat3nBxlPyaM8XliyPREVkTo3U38x3StOt8HaySSF7NZ33bswPhPsECdPb/b5brj1WZ4jfHH/1gj/OZ3s1uwSL1jlnFweZ0OPIC1RA8cDgLnfJ3YCcEDvQ+ZPGYP48DUTXWAQSUsafjgvc4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
